// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1773920100);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1773920100);
user_pref("app.update.lastUpdateTime.region-update-timer", 1773920100);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1773920100);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1773920130);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1773920100);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.memory.enable", true);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 150);
user_pref("browser.newtabpage.activity-stream.impressionId", "{bc69f149-3f2d-4157-aa51-d50facf06ae7}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "never");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\",\"webcompat@mozilla.org\",\"screenshots@mozilla.org\",\"pictureinpicture@mozilla.org\",\"formautofill@mozilla.org\"]");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.sessionhistory.max_entries", 10);
user_pref("browser.sessionhistory.max_total_viewers", -1);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20250315105650");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.lastColdStartupCheck", 1773923243);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":21,\"newElementCount\":2}");
user_pref("captchadetection.lastSubmission", 1773920);
user_pref("datareporting.dau.cachedUsageProfileID", "beefbeef-beef-beef-beef-beeefbeefbee");
user_pref("distribution.iniFile.exists.appversion", "135.0.1-beta.24");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.filesystem.pathcheck.disabled", true);
user_pref("dom.webdriver.enabled", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.formautofill.creditCards.reauth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECNNO754LUqSRBAhwM9UYAnfT4g==");
user_pref("extensions.lastAppBuildId", "20250315105650");
user_pref("extensions.lastAppVersion", "135.0.1-beta.24");
user_pref("extensions.lastPlatformVersion", "135.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"bce36b34-22fd-43ba-a635-c0ddcd2c5d1e\",\"pictureinpicture@mozilla.org\":\"2b5ffbc8-c818-48c5-aa9c-304d7dcf5195\",\"screenshots@mozilla.org\":\"20843672-ba7e-423c-b36f-acc792db5f10\",\"webcompat@mozilla.org\":\"bfaaddc0-f8f3-45d2-b987-2426d0061a89\",\"firefox-compact-dark@mozilla.org\":\"f55b2e57-5e90-49a4-9aa0-2a10c7eef4ef\",\"uBlock0@raymondhill.net\":\"11773ed8-dec1-473e-aaa9-24be3c2a9887\",\"addons-search-detection@mozilla.com\":\"ed37a4f3-c3db-43ad-a8c0-c37691e76d66\"}");
user_pref("font.system.whitelist", "Arial,Arial Black,Bahnschrift,Calibri,Calibri Light,Cambria,Cambria Math,Candara,Candara Light,Comic Sans MS,Consolas,Constantia,Corbel,Corbel Light,Courier New,Ebrima,Franklin Gothic Medium,Gabriola,Gadugi,Georgia,HoloLens MDL2 Assets,Impact,Ink Free,Javanese Text,Leelawadee UI,Leelawadee UI Semilight,Lucida Console,Lucida Sans Unicode,MS Gothic,MS PGothic,MS UI Gothic,MV Boli,Malgun Gothic,Malgun Gothic Semilight,Marlett,Microsoft Himalaya,Microsoft JhengHei,Microsoft JhengHei Light,Microsoft JhengHei UI,Microsoft JhengHei UI Light,Microsoft New Tai Lue,Microsoft PhagsPa,Microsoft Sans Serif,Microsoft Tai Le,Microsoft YaHei,Microsoft YaHei Light,Microsoft YaHei UI,Microsoft YaHei UI Light,Microsoft Yi Baiti,MingLiU-ExtB,MingLiU_HKSCS-ExtB,Mongolian Baiti,Myanmar Text,NSimSun,Nirmala UI,Nirmala UI Semilight,PMingLiU-ExtB,Palatino Linotype,Segoe Fluent Icons,Segoe MDL2 Assets,Segoe Print,Segoe Script,Segoe UI,Segoe UI Black,Segoe UI Emoji,Segoe UI Historic,Segoe UI Light,Segoe UI Semibold,Segoe UI Semilight,Segoe UI Symbol,Segoe UI Variable,SimSun,SimSun-ExtB,Sitka,Sitka Text,Sylfaen,Symbol,Tahoma,Times New Roman,Trebuchet MS,Twemoji Mozilla,Verdana,Webdings,Wingdings,Yu Gothic,Yu Gothic Light,Yu Gothic Medium,Yu Gothic UI,Yu Gothic UI Light,Yu Gothic UI Semibold,Yu Gothic UI Semilight,宋体,微軟正黑體,微軟正黑體 Light,微软雅黑,微软雅黑 Light,新宋体,新細明體-ExtB,游ゴシック,游ゴシック Light,游ゴシック Medium,細明體-ExtB,細明體_HKSCS-ExtB,맑은 고딕,맑은 고딕 Semilight,ＭＳ ゴシック,ＭＳ Ｐゴシック");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("general.appversion.override", "");
user_pref("general.platform.override", "");
user_pref("media.getdisplaymedia.screencapturekit.enabled", false);
user_pref("media.getdisplaymedia.screencapturekit.picker.enabled", false);
user_pref("media.gmp-manager.buildID", "20250315105650");
user_pref("media.gmp-manager.lastCheck", 1773920289);
user_pref("media.gmp-manager.lastEmptyCheck", 1773920289);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs2", true);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.warn_unprivileged_namespaces", false);
user_pref("sidebar.backupState", "{\"width\":\"\",\"command\":\"\",\"expanded\":false,\"hidden\":true}");
user_pref("signon.management.page.os-auth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECOWdzT3B2DqyBAhsBDJusUfG4Q==");
user_pref("toolkit.startup.last_success", 1773923236);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.cachedProfileGroupID", "decafdec-afde-cafd-ecaf-decafdecafde");
user_pref("toolkit.telemetry.previousBuildID", "20250315105650");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("useragentoverride", "");
user_pref("webgl.force-enabled", true);
