name: ✨ Feature Request
description: Suggest a new feature or enhancement for HeadlessX
title: '[Feature]: '
labels: ['enhancement', 'feature-request']
assignees: ['saifyxpro']

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request
        
        Thank you for suggesting a feature! Your ideas help make HeadlessX better.
        
        **Before submitting:** Please search existing issues to see if someone has already suggested this feature.

  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: Preliminary Checks
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues for similar feature requests
          required: true
        - label: I have checked the roadmap documentation
          required: true
        - label: This feature aligns with HeadlessX's purpose and ethics

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - Anti-detection/Fingerprinting
        - Browser automation
        - API endpoints
        - Security/Privacy
        - Performance optimization
        - Developer experience
        - Documentation
        - Configuration/Setup
        - Monitoring/Analytics
        - Other (specify below)
    validations:
      required: true

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A brief, clear summary of the feature
      placeholder: What feature would you like to see added?
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: What problem does this feature solve?
      placeholder: |
        Describe the problem you're trying to solve:
        - What limitations are you encountering?
        - What use cases are not currently supported?
        - How does this impact your workflow?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your preferred solution in detail
      placeholder: |
        How should this feature work?
        - What API endpoints would be needed?
        - What configuration options should be available?
        - How should it integrate with existing features?
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: |
        What other approaches have you considered?
        - Workarounds you've tried
        - Other tools that provide this functionality
        - Different implementation approaches

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking current projects)
        - High (significantly improves workflow)
        - Medium (nice to have)
        - Low (would use occasionally)
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (configuration change, minor addition)
        - Medium (new endpoint, moderate code changes)
        - Complex (major architectural changes)
        - Unsure

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases for this feature
      placeholder: |
        1. As a privacy researcher, I want to... so that I can...
        2. As a developer, I need to... in order to...
        3. When testing websites, this feature would help me...

  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: Any specific technical requirements or constraints?
      placeholder: |
        - Performance requirements
        - Compatibility considerations
        - Security implications
        - Dependencies needed

  - type: checkboxes
    id: ethical-considerations
    attributes:
      label: Ethical Considerations
      description: Please confirm this feature aligns with HeadlessX's ethical guidelines
      options:
        - label: This feature supports legitimate use cases (research, testing, privacy protection)
        - label: This feature does not enable fraud, abuse, or illegal activities
        - label: I have considered the privacy implications of this feature
        - label: This feature respects website terms of service and robots.txt

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        Example API calls, configuration snippets, or code examples:
        
        ```bash
        # Example usage
        curl -X POST http://localhost:3000/api/new-feature \
          -H "Authorization: Bearer token" \
          -d '{"parameter": "value"}'
        ```

  - type: dropdown
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes?
      options:
        - No breaking changes expected
        - Minor breaking changes acceptable
        - Major breaking changes required
        - Unsure about breaking changes

  - type: checkboxes
    id: contribution-offer
    attributes:
      label: Contribution
      description: How can you help with this feature?
      options:
        - label: I can help design the feature
        - label: I can contribute code implementation
        - label: I can help with testing
        - label: I can assist with documentation
        - label: I can provide ongoing feedback

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information about this feature request
      placeholder: |
        - Links to relevant research or documentation
        - Screenshots or mockups
        - Related issues or discussions
        - Timeline considerations