name: Docs Check
on:
  push:
    branches: [main]
    paths: ['docs/**', '*.md']
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Docs checked"
